apiVersion: v1
kind: ConfigMap
metadata:
  name: store-front-nginx-conf
data:
  default.conf: |
    server {
        listen       8080;
        listen  [::]:8080;
        server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /api/products {
            set $product_service http://product-service.pets.svc.cluster.local:3002;
            proxy_pass $product_service/;
        }

        location /api/orders {
            # NOTE: service name is order-service (not orders-service)
            set $order_service http://order-service.pets.svc.cluster.local:3000;
            proxy_pass $order_service/;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
