apiVersion: v1
kind: ConfigMap
metadata:
  name: store-front-nginx-conf
data:
  default.conf: |
    server {
      listen 8080;
      server_name localhost;

      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api/products {
        proxy_pass http://product-service:3002;
      }

      location /api/categories {
        proxy_pass http://product-service:3002;
      }

      location /api/orders {
        proxy_pass http://orders-service:3000;
      }

      location /api/checkout {
        proxy_pass http://checkout-service:3004;
      }

      location /api/makeline {
        proxy_pass http://makeline-service:3001;
      }

      location /api/ai {
        proxy_pass http://ai-service:5001;
      }

      location /api/health {
        return 200;
      }
    }
